### ISSUE TITLE
winnow::error::convert_error overpromises in its type signature

### ISSUE THREAD

**Issue by fishface60** [winnow-rs/winnow#261]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.4.6

### Describe your use case

I am using winnow to implement `FromStr` as described in [winnow::_topic::fromstr](https://docs.rs/winnow/latest/winnow/_topic/fromstr/index.html).
The documentation of `VerboseError` suggested I try [winnow::error::convert_error](https://docs.rs/winnow/latest/winnow/error/fn.convert_error.html).
Since implementing `FromStr` requires using [winnow::error::VerboseError::to_owned](https://docs.rs/winnow/latest/winnow/error/struct.VerboseError.html#method.to_owned) the inner errors are using String.
I naively passed a String copy of my input in order to satisfy the type discrepancy, resulting in a panic because offset_to was producing indexes beyond the length of the input, since the implicit bound that the error contains substrings of the input wasn't made explicit in the documentation or type system.

### Describe the solution you'd like

Some owned error type that contains everything convert_error would render, failing that, updating the FromStr guide to use convert_error and String as the error type.

### Alternatives, if applicable

Document the limitations of convert_error, or strengthen the trait bounds to ensure the input and errors are from the same object.

**Comment by epage** [comment]
Note: we plan to revamp the "nice" error in #103, so I would lean towards any change there until or as part of that.

> Since implementing FromStr requires using [winnow::error::VerboseError::to_owned](https://docs.rs/winnow/latest/winnow/error/struct.VerboseError.html#method.to_owned) the inner errors are using String.

The use of  `winnow::error::convert_error` for `VerboseError` would be in place of `winnow::error::Error::into_owned` for `Error`.

> Some owned error type that contains everything convert_error would render, 

That wouldn't make sense because the intention is to use borrowed types within the parser for performance and then to switch to an owned type on the edge, whether that is rendering it to a `String` with `convert_error` or literally changing the types to be owned like in the example.

>  updating the FromStr guide to use convert_error and String as the error type.

This would mean switching the guide to `VerboseError` which would then not service other people.  The question is how to communicate the boundary situation and *where* that should be communicated.  I think the ["Integrating the Parser"](https://docs.rs/winnow/latest/winnow/_tutorial/chapter_7/index.html) section of the tutorial could be expanded to better explain the situation and options.

> Document the limitations of convert_error, 

This isn't quite hitting on the fundamental problem communication problem in the API reference.  `convert_error` expects to receive the `Stream`s but instead something else was passed in.  Below I mention an alternative trait bound approach that I think helps clear this up inline to the API definition but we'll have to see.

> strengthen the trait bounds to ensure the input and errors are from the same object.

I think we could require them to be `Stream` which shouldn't be restrictive to people and should prevent an owned type from being passed in.  However, that doesn't strictly require them to be the same object.

Strictly speaking, this would be a breaking change and would have to wait for the current breaking release to come out.

**Comment by epage** [comment]
`convert_error` is gone in the new version
