### ISSUE TITLE
Context for built-in combinators

### ISSUE THREAD

**Issue by judemille** [winnow-rs/winnow#421]
### Please complete the following tasks

- [X] I have searched the [discussions](https://github.com/winnow-rs/winnow/discussions)
- [X] I have searched the [open](https://github.com/winnow-rs/winnow/issues) and [rejected](https://github.com/winnow-rs/winnow/issues?q=is%3Aissue+label%3AS-wont-fix+is%3Aclosed) issues

### winnow version

0.5.34

### Describe your use case

Using Winnow without adding `.context(...)` calls to every combinator.

### Describe the solution you'd like

Context should be added to [built-in combinators](https://docs.rs/winnow/latest/winnow/combinator/index.html), so that when they produce an error, the `Display` impl indicates *what* went wrong and *why*, without having to trace the parsing.

I can help with implementation, once details are worked out.

### Alternatives, if applicable

Forcing users to add context calls to each use of every combinator, as current, but that is really not ideal.

### Additional Context

This may be difficult, due to the complexities of `AddContext`. I'm not sure how best to implement this.

**Comment by epage** [comment]
This was an intentional choice.  `toml_edit` originally used `combine` which would automatically determine what was expected.  The problem was that it was slow (because you couldn't opt-out of what we're getting in #415) and the quality was low.  I found that hand-specifying the values gives much better results.

This comes at the cost of not getting great errors in more trivial / prototype cases.

The other problem with baking them in is that it would tie us to one specific type context type.  Currently, we offer a default choice but allow people to customize it (which the author of #415 seems to do).

**Comment by judemille** [comment]
Yeah, I'm not sure how to solve that issue. I figure there must be a good way to go about it, but I'm at a loss.

**Comment by epage** [comment]
Oh and a third problem is our own context might interfere with the context the developer is creating around winnow.

I feel like there are contradictory needs here and I am leaning towards closing this. If there is a reason for us to re-evaluate this, let us know!
